### ISSUE TITLE
Melhor animação de hover

### ISSUE THREAD

**Issue by Gustavo-Cauzzi** [Muchinha/To-do-list#1]
Sugiro trocar a animação de hover do .todo__item para o seguinte código
```css
.todo__item:hover {
  border-width: thick;
  box-shadow: 1px 7px 15px 3px var(--secondary-color);
  width: 105%;
  height: 65px;
  margin-left: -2.5%;
}
```

Assim teremos uma animação mais agradável para a UI!
